### ISSUE TITLE
[기능개발] Map

### ISSUE THREAD

**Issue by sudong1004** [bitcamp-homies/caffeine-frontend#3]

**Comment by poonghyeok** [comment]
### 클론 (혹은 개발예정) 중인 페이지의 URL을 입력해주세요.
- https://app.starbucks.com/store-locator?map=37.491942,127.030386,15z

### 해당 이슈에서 작업할 내용을 작성해주세요.
- 인덱스 페이지 레이아웃 설정
- 상단 navBar 생성
 
### 참고사항 혹은 작업 내용에 대한 스크린샷 (선택)
